#!/bin/bash
echo "Enter the file name to search in the current directory:"
read filename

if [ -f "./$filename" ]; then
    echo "file exists!"
    ls -l $filename
else
    echo "file does not exists!"
fi
