#!/bin/bash
echo "Enter the file name to search in the current directory:"
read filename

if [ -f "./$filename" ]; then
    echo "Файл существует!"
    ls -l $filename
else
    echo "Файл не существует!"
fi
